CREATE TABLE USERS 
(
  USERID INT NOT NULL 
, EMAIL VARCHAR2(100) NOT NULL 
, FIRSTNAME VARCHAR2(50) NOT NULL 
, LASTNAME VARCHAR2(50) NOT NULL 
, DATEOFBIRTH DATE NOT NULL 
, CITY VARCHAR2(20) NOT NULL 
, STATE VARCHAR2(20) 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USERID 
  )
  ENABLE 
);
